# Generated by Django 4.0.4 on 2022-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itobj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itobject',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itobject',
            name='trending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itobject',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
